### PR TITLE
Add implementation to wrap ASP binaries.

### PR DESCRIPTION
**Pull request by jomey**
Add wrappers for ASP stereo commands. The base Stereo class wraps the
'stereo' command itself, while the subclass StereoSGM is changed to use
'parallel_stereo'.

### CODE REVIEW

**Comment by ShashankBice** [comment]
Do we always need to do parallel stereo with SGM/MGM ? If the image size fits computationally solvable corr-tile-size, then normal stereo should suffice and we will be able to avoid the blending operation. Maybe a flag can be added at some point, but good for now :)

**Comment by jomey** [comment]
> Do we always need to do parallel stereo with SGM/MGM ? If the image size fits computationally solvable corr-tile-size, then normal stereo should suffice and we will be able to avoid the blending operation. Maybe a flag can be added at some point, but good for now :)

Are you mostly using non parallel stereo, when choosing SGM/MGM?

**Comment by ShashankBice** [comment]
> > Do we always need to do parallel stereo with SGM/MGM ? If the image size fits computationally solvable corr-tile-size, then normal stereo should suffice and we will be able to avoid the blending operation. Maybe a flag can be added at some point, but good for now :)
> 
> Are you mostly using non parallel stereo, when choosing SGM/MGM?

Depending on use case. I use parallel when with DG, or other bigger image sizes. For Skysat, I just use stereo.

**Comment by jomey** [comment]
@ShashankBice - I made the change as you suggested. `stereo` is now the default for SGM and you can make it parallel by passing that option and specify the number of processes.

**Pull request closed without merging**
